package Interfaz;

import SQL.HikariJDBC;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class PantallaDeModificacion extends javax.swing.JFrame {

    String tipo;

    public PantallaDeModificacion(
            String cedula, String nombre, String fechanacimiento, String genero,
            String correo, String telefono, String provincia, String ciudad, String corregimiento,
            String nummembresia, String cantidadpromediogastada, String productosfrecuentes,
            String descuento, String asesorasignado, String cantidadcredito, String tipo
    ) {
        initComponents();
        this.tipo = tipo;
        if ("Cliente Ocasional".equals(tipo)) {

            this.cedulaCliente.setText(cedula);
            this.nombreCliente.setText(nombre);
            this.fechaNacimientoCliente.setText(fechanacimiento);
            this.generoCliente.setSelectedItem(genero);
            this.correoCliente.setText(correo);
            this.telefonoCliente.setText(telefono);
            this.provinciaCliente.setText(provincia);
            this.ciudadCliente.setText(ciudad);
            this.corregimientoCliente.setText(corregimiento);

        } else if ("Cliente Frecuente".equals(tipo)) {

            this.cedulaCliente.setText(cedula);
            this.nombreCliente.setText(nombre);
            this.fechaNacimientoCliente.setText(fechanacimiento);
            this.generoCliente.setSelectedItem(genero);
            this.correoCliente.setText(correo);
            this.telefonoCliente.setText(telefono);
            this.provinciaCliente.setText(provincia);
            this.ciudadCliente.setText(ciudad);
            this.corregimientoCliente.setText(corregimiento);
            this.numeroMembresia.setText(nummembresia);
            this.promedioGastado.setText(cantidadpromediogastada);
            this.productoFrecuentes.setText(productosfrecuentes);
            this.productoDescuento.setText(descuento);

        } else if ("Cliente VIP".equals(tipo)) {
            this.cedulaCliente.setText(cedula);
            this.nombreCliente.setText(nombre);
            this.fechaNacimientoCliente.setText(fechanacimiento);
            this.generoCliente.setSelectedItem(genero);
            this.correoCliente.setText(correo);
            this.telefonoCliente.setText(telefono);
            this.provinciaCliente.setText(provincia);
            this.ciudadCliente.setText(ciudad);
            this.corregimientoCliente.setText(corregimiento);
            this.numeroMembresia.setText(nummembresia);
            this.promedioGastado.setText(cantidadpromediogastada);
            this.productoFrecuentes.setText(productosfrecuentes);
            this.productoDescuento.setText(descuento);
            this.asesorAsignadoV.setText(asesorasignado);
            this.cantidadCreditoV.setText(cantidadcredito);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombreCliente = new javax.swing.JTextField();
        fechaNacimientoCliente = new javax.swing.JTextField();
        telefonoCliente = new javax.swing.JTextField();
        correoCliente = new javax.swing.JTextField();
        registrarV = new javax.swing.JButton();
        cancelarV = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cedulaCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        generoCliente = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        provinciaCliente = new javax.swing.JTextField();
        ciudadCliente = new javax.swing.JTextField();
        corregimientoCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        numeroMembresia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        productoDescuento = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        promedioGastado = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        asesorAsignadoV = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        productoFrecuentes = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cantidadCreditoV = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Modificacion de Cliente ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel3)
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Nombre:");

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("Fecha de nacimiento:");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setText("Teléfono:");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 204));
        jLabel5.setText("Correo:");

        nombreCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        nombreCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true));
        nombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreClienteActionPerformed(evt);
            }
        });

        fechaNacimientoCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        fechaNacimientoCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true));
        fechaNacimientoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaNacimientoClienteActionPerformed(evt);
            }
        });

        telefonoCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        telefonoCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true));
        telefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoClienteActionPerformed(evt);
            }
        });

        correoCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        correoCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true));
        correoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoClienteActionPerformed(evt);
            }
        });

        registrarV.setBackground(new java.awt.Color(0, 153, 204));
        registrarV.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        registrarV.setForeground(new java.awt.Color(255, 255, 255));
        registrarV.setText("Registrar");
        registrarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarVActionPerformed(evt);
            }
        });

        cancelarV.setBackground(new java.awt.Color(153, 0, 0));
        cancelarV.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        cancelarV.setForeground(new java.awt.Color(255, 255, 255));
        cancelarV.setText("Cancelar");
        cancelarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarVActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 255));
        jLabel9.setText("Cédula:");

        cedulaCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        cedulaCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true));
        cedulaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaClienteActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("Género:");

        generoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        generoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoClienteActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 204));
        jLabel7.setText("Provincia:");

        provinciaCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        provinciaCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true));
        provinciaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinciaClienteActionPerformed(evt);
            }
        });

        ciudadCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        ciudadCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true));
        ciudadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadClienteActionPerformed(evt);
            }
        });

        corregimientoCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        corregimientoCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true));
        corregimientoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corregimientoClienteActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 204));
        jLabel8.setText("Ciudad:");

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 204));
        jLabel10.setText("Corregimiento:");

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 255));
        jLabel11.setText("Número de Membresía:");

        numeroMembresia.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        numeroMembresia.setForeground(new java.awt.Color(0, 0, 0));
        numeroMembresia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 255));
        jLabel12.setText("Producto Descuento:");

        productoDescuento.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        productoDescuento.setForeground(new java.awt.Color(0, 0, 0));
        productoDescuento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 255));
        jLabel13.setText("Promedio Gastado:");

        promedioGastado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        promedioGastado.setForeground(new java.awt.Color(0, 0, 0));
        promedioGastado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 255));
        jLabel14.setText("Asesor Asignado:");

        asesorAsignadoV.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        asesorAsignadoV.setForeground(new java.awt.Color(0, 0, 0));
        asesorAsignadoV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 255));
        jLabel15.setText("Productos Frecuentes:");

        productoFrecuentes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        productoFrecuentes.setForeground(new java.awt.Color(0, 0, 0));
        productoFrecuentes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 255));
        jLabel16.setText("Cantidad Crédito:");

        cantidadCreditoV.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        cantidadCreditoV.setForeground(new java.awt.Color(0, 0, 0));
        cantidadCreditoV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(registrarV)
                                .addGap(34, 34, 34)
                                .addComponent(cancelarV))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productoDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(promedioGastado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(generoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fechaNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(correoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(106, 106, 106)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(corregimientoCliente))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(47, 47, 47)
                                                .addComponent(ciudadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(telefonoCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cedulaCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(provinciaCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(numeroMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(productoFrecuentes, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel14))
                                        .addGap(49, 49, 49)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cantidadCreditoV, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                            .addComponent(asesorAsignadoV))))))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fechaNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(telefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(generoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(provinciaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(correoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ciudadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(corregimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(numeroMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(productoDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(asesorAsignadoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(promedioGastado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(cantidadCreditoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registrarV)
                            .addComponent(cancelarV))
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(productoFrecuentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 475, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreClienteActionPerformed

    }//GEN-LAST:event_nombreClienteActionPerformed

    private void fechaNacimientoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaNacimientoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaNacimientoClienteActionPerformed

    private void telefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoClienteActionPerformed

    private void correoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoClienteActionPerformed

    private void registrarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarVActionPerformed
        if ("Cliente Ocasional".equals(tipo)) {
            System.out.println(tipo);

            String nuevaCedula = cedulaCliente.getText();
            String nuevoNombre = nombreCliente.getText();
            String nuevaFechaNacimiento = fechaNacimientoCliente.getText();
            String nuevoGenero = (String) generoCliente.getSelectedItem();
            String nuevoCorreo = correoCliente.getText();
            String nuevoTelefono = telefonoCliente.getText();
            String nuevaProvincia = provinciaCliente.getText();
            String nuevaCiudad = ciudadCliente.getText();
            String nuevoCorregimiento = corregimientoCliente.getText();

            try {
                Connection con = HikariJDBC.getConnection();
                PreparedStatement ps = con.prepareStatement("UPDATE clientes SET nombre=?, fechaNacimiento=?, genero=?, correo=?, telefono=?, provincia=?, ciudad=?, corregimiento=? WHERE cedula=?");

                ps.setString(1, nuevoNombre);
                ps.setString(2, nuevaFechaNacimiento);
                ps.setString(3, nuevoGenero);
                ps.setString(4, nuevoCorreo);
                ps.setString(5, nuevoTelefono);
                ps.setString(6, nuevaProvincia);
                ps.setString(7, nuevaCiudad);
                ps.setString(8, nuevoCorregimiento);
                ps.setString(9, nuevaCedula);

                int filasActualizadas = ps.executeUpdate();

                if (filasActualizadas > 0) {
                    JOptionPane.showMessageDialog(this, "Datos actualizados correctamente en la base de datos.");
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo actualizar los datos en la base de datos.");
                }

                ps.close();
                con.close();

            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        } else if ("Cliente Frecuente".equals(tipo)) {
            System.out.println(tipo);

            String nuevaCedula = cedulaCliente.getText();
            String nuevoNombre = nombreCliente.getText();
            String nuevaFechaNacimiento = fechaNacimientoCliente.getText();
            String nuevoGenero = (String) generoCliente.getSelectedItem();
            String nuevoCorreo = correoCliente.getText();
            String nuevoTelefono = telefonoCliente.getText();
            String nuevaProvincia = provinciaCliente.getText();
            String nuevaCiudad = ciudadCliente.getText();
            String nuevoCorregimiento = corregimientoCliente.getText();

            String nuevoNumMembresia = numeroMembresia.getText();
            String nuevaCantidadPromedioGastada = promedioGastado.getText();
            String nuevoProductosFrecuentes = productoFrecuentes.getText();
            String nuevoDescuento = productoDescuento.getText();

            try {
                Connection con = HikariJDBC.getConnection();
                PreparedStatement ps = con.prepareStatement("UPDATE clientes SET nombre=?, fechaNacimiento=?, genero=?, correo=?, telefono=?, provincia=?, ciudad=?, corregimiento=?, numMembresia=?, cantidadPromedioGastada=?, productosFrecuentes=?, descuento=? WHERE cedula=?");

                ps.setString(1, nuevoNombre);
                ps.setString(2, nuevaFechaNacimiento);
                ps.setString(3, nuevoGenero);
                ps.setString(4, nuevoCorreo);
                ps.setString(5, nuevoTelefono);
                ps.setString(6, nuevaProvincia);
                ps.setString(7, nuevaCiudad);
                ps.setString(8, nuevoCorregimiento);
                ps.setString(9, nuevoNumMembresia);
                ps.setString(10, nuevaCantidadPromedioGastada);
                ps.setString(11, nuevoProductosFrecuentes);
                ps.setString(12, nuevoDescuento);
                ps.setString(13, nuevaCedula);

                int filasActualizadas = ps.executeUpdate();

                if (filasActualizadas > 0) {
                    JOptionPane.showMessageDialog(this, "Datos actualizados correctamente en la base de datos.");
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo actualizar los datos en la base de datos.");
                }

                ps.close();
                con.close();

            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        } else if ("Cliente VIP".equals(tipo)) {
            System.out.println(tipo);

            String nuevaCedula = cedulaCliente.getText();
            String nuevoNombre = nombreCliente.getText();
            String nuevaFechaNacimiento = fechaNacimientoCliente.getText();
            String nuevoGenero = (String) generoCliente.getSelectedItem();
            String nuevoCorreo = correoCliente.getText();
            String nuevoTelefono = telefonoCliente.getText();
            String nuevaProvincia = provinciaCliente.getText();
            String nuevaCiudad = ciudadCliente.getText();
            String nuevoCorregimiento = corregimientoCliente.getText();

            String nuevoNumMembresia = numeroMembresia.getText();
            String nuevaCantidadPromedioGastada = promedioGastado.getText();
            String nuevoProductosFrecuentes = productoFrecuentes.getText();
            String nuevoDescuento = productoDescuento.getText();
            String nuevoAsesorAsignado = asesorAsignadoV.getText();
            String nuevaCantidadCredito = cantidadCreditoV.getText();

            try {
                Connection con = HikariJDBC.getConnection();
                PreparedStatement ps = con.prepareStatement("UPDATE clientes SET nombre=?, fechaNacimiento=?, genero=?, correo=?, telefono=?, provincia=?, ciudad=?, corregimiento=?, numMembresia=?, cantidadPromedioGastada=?, productosFrecuentes=?, descuento=?, asesorAsignado=?, cantidadCredito=? WHERE cedula=?");

                ps.setString(1, nuevoNombre);
                ps.setString(2, nuevaFechaNacimiento);
                ps.setString(3, nuevoGenero);
                ps.setString(4, nuevoCorreo);
                ps.setString(5, nuevoTelefono);
                ps.setString(6, nuevaProvincia);
                ps.setString(7, nuevaCiudad);
                ps.setString(8, nuevoCorregimiento);
                ps.setString(9, nuevoNumMembresia);
                ps.setString(10, nuevaCantidadPromedioGastada);
                ps.setString(11, nuevoProductosFrecuentes);
                ps.setString(12, nuevoDescuento);
                ps.setString(13, nuevoAsesorAsignado);
                ps.setString(14, nuevaCantidadCredito);
                ps.setString(15, nuevaCedula);

                int filasActualizadas = ps.executeUpdate();

                if (filasActualizadas > 0) {
                    JOptionPane.showMessageDialog(this, "Datos actualizados correctamente en la base de datos.");
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo actualizar los datos en la base de datos.");
                }

                ps.close();
                con.close();

            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_registrarVActionPerformed

    private void cancelarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarVActionPerformed
        dispose();
    }//GEN-LAST:event_cancelarVActionPerformed

    private void cedulaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaClienteActionPerformed

    private void generoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoClienteActionPerformed
        String genero[] = {"M", "F"};

        for (String g : genero) {
            generoCliente.addItem(g);
        }
    }//GEN-LAST:event_generoClienteActionPerformed

    private void provinciaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinciaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provinciaClienteActionPerformed

    private void ciudadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadClienteActionPerformed

    private void corregimientoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corregimientoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_corregimientoClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaDeModificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaDeModificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaDeModificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaDeModificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PantallaDeModificacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField asesorAsignadoV;
    private javax.swing.JButton cancelarV;
    private javax.swing.JTextField cantidadCreditoV;
    private javax.swing.JTextField cedulaCliente;
    private javax.swing.JTextField ciudadCliente;
    private javax.swing.JTextField corregimientoCliente;
    private javax.swing.JTextField correoCliente;
    private javax.swing.JTextField fechaNacimientoCliente;
    private javax.swing.JComboBox<String> generoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombreCliente;
    private javax.swing.JTextField numeroMembresia;
    private javax.swing.JTextField productoDescuento;
    private javax.swing.JTextField productoFrecuentes;
    private javax.swing.JTextField promedioGastado;
    private javax.swing.JTextField provinciaCliente;
    private javax.swing.JButton registrarV;
    private javax.swing.JTextField telefonoCliente;
    // End of variables declaration//GEN-END:variables
}
