package Interfaz;

import SQL.HikariJDBC;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class RegistroDeClienteFrecuente extends javax.swing.JFrame {

    String tipoF;
    
    public RegistroDeClienteFrecuente(String tipo) { 
        this.tipoF = tipo;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        nombreClienteFrecuente = new javax.swing.JTextField();
        fechaNacimientoClienteFrecuente = new javax.swing.JTextField();
        telefonoClienteFrecuente = new javax.swing.JTextField();
        correoClienteFrecuente = new javax.swing.JTextField();
        registrarF = new javax.swing.JButton();
        cancelarF = new javax.swing.JButton();
        jLabel66 = new javax.swing.JLabel();
        cedulaClienteFrecuente = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        generoClienteFrecuente = new javax.swing.JComboBox<>();
        jLabel68 = new javax.swing.JLabel();
        provinciaClienteFrecuente = new javax.swing.JTextField();
        ciudadClienteFrecuente = new javax.swing.JTextField();
        corregimientoClienteFrecuente = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        numeroMembresiaFrecuente = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        productoDescuentoFrecuente = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        productoFrecuentes = new javax.swing.JTextField();
        promedioGastadoFrecuente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registro de Cliente Frecuente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel3)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel62.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(0, 153, 255));
        jLabel62.setText("Nombre:");

        jLabel63.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(0, 153, 204));
        jLabel63.setText("Fecha de nacimiento:");

        jLabel64.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(0, 153, 204));
        jLabel64.setText("Teléfono:");

        jLabel65.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(0, 153, 204));
        jLabel65.setText("Correo:");

        nombreClienteFrecuente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        nombreClienteFrecuente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true));
        nombreClienteFrecuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCliente2ActionPerformed(evt);
            }
        });

        fechaNacimientoClienteFrecuente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        fechaNacimientoClienteFrecuente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true));
        fechaNacimientoClienteFrecuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaNacimientoClienteActionPerformed(evt);
            }
        });

        telefonoClienteFrecuente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        telefonoClienteFrecuente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true));
        telefonoClienteFrecuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoClienteActionPerformed(evt);
            }
        });

        correoClienteFrecuente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        correoClienteFrecuente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true));
        correoClienteFrecuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoClienteActionPerformed(evt);
            }
        });

        registrarF.setBackground(new java.awt.Color(0, 153, 204));
        registrarF.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        registrarF.setForeground(new java.awt.Color(255, 255, 255));
        registrarF.setText("Registrar");
        registrarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        cancelarF.setBackground(new java.awt.Color(153, 0, 0));
        cancelarF.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        cancelarF.setForeground(new java.awt.Color(255, 255, 255));
        cancelarF.setText("Cancelar");
        cancelarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        jLabel66.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(0, 153, 255));
        jLabel66.setText("Cédula:");

        cedulaClienteFrecuente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        cedulaClienteFrecuente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true));
        cedulaClienteFrecuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaCliente1ActionPerformed(evt);
            }
        });

        jLabel67.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(0, 153, 255));
        jLabel67.setText("Género:");

        generoClienteFrecuente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        generoClienteFrecuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoClienteActionPerformed(evt);
            }
        });

        jLabel68.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(0, 153, 204));
        jLabel68.setText("Provincia:");

        provinciaClienteFrecuente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        provinciaClienteFrecuente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true));
        provinciaClienteFrecuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinciaClienteActionPerformed(evt);
            }
        });

        ciudadClienteFrecuente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        ciudadClienteFrecuente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true));
        ciudadClienteFrecuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadClienteActionPerformed(evt);
            }
        });

        corregimientoClienteFrecuente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        corregimientoClienteFrecuente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true));
        corregimientoClienteFrecuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corregimientoClienteActionPerformed(evt);
            }
        });

        jLabel69.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(0, 153, 204));
        jLabel69.setText("Ciudad:");

        jLabel70.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(0, 153, 204));
        jLabel70.setText("Corregimiento:");

        jLabel71.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(0, 153, 255));
        jLabel71.setText("Número de Membresía:");

        numeroMembresiaFrecuente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        numeroMembresiaFrecuente.setForeground(new java.awt.Color(0, 0, 0));
        numeroMembresiaFrecuente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));

        jLabel72.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(0, 153, 255));
        jLabel72.setText("Producto Descuento:");

        productoDescuentoFrecuente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        productoDescuentoFrecuente.setForeground(new java.awt.Color(0, 0, 0));
        productoDescuentoFrecuente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));

        jLabel73.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(0, 153, 255));
        jLabel73.setText("Promedio Gastado:");

        jLabel74.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(0, 153, 255));
        jLabel74.setText("Productos Frecuentes:");

        productoFrecuentes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        productoFrecuentes.setForeground(new java.awt.Color(0, 0, 0));
        productoFrecuentes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));

        promedioGastadoFrecuente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        promedioGastadoFrecuente.setForeground(new java.awt.Color(0, 0, 0));
        promedioGastadoFrecuente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel71)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(registrarF)
                                .addGap(34, 34, 34)
                                .addComponent(cancelarF))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel72)
                                .addGap(25, 25, 25)
                                .addComponent(productoDescuentoFrecuente, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel67)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(generoClienteFrecuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(numeroMembresiaFrecuente, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel73)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(promedioGastadoFrecuente, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel74)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(productoFrecuentes, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel62)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nombreClienteFrecuente, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel63)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fechaNacimientoClienteFrecuente, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel65)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(correoClienteFrecuente, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(106, 106, 106)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel70)
                                        .addGap(18, 18, 18)
                                        .addComponent(corregimientoClienteFrecuente))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel64)
                                            .addComponent(jLabel66)
                                            .addComponent(jLabel68)
                                            .addComponent(jLabel69))
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addGap(47, 47, 47)
                                                .addComponent(ciudadClienteFrecuente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(telefonoClienteFrecuente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cedulaClienteFrecuente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(provinciaClienteFrecuente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(nombreClienteFrecuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel66)
                    .addComponent(cedulaClienteFrecuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63)
                    .addComponent(fechaNacimientoClienteFrecuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel64)
                    .addComponent(telefonoClienteFrecuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel67)
                    .addComponent(generoClienteFrecuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel68)
                    .addComponent(provinciaClienteFrecuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel65)
                        .addComponent(correoClienteFrecuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ciudadClienteFrecuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel69)))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel70)
                    .addComponent(corregimientoClienteFrecuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71)
                    .addComponent(numeroMembresiaFrecuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel74)
                    .addComponent(productoFrecuentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72)
                    .addComponent(productoDescuentoFrecuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel73)
                    .addComponent(promedioGastadoFrecuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarF)
                    .addComponent(cancelarF))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(425, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void corregimientoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corregimientoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_corregimientoClienteActionPerformed

    private void ciudadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadClienteActionPerformed

    private void provinciaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinciaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provinciaClienteActionPerformed

    private void generoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoClienteActionPerformed

    private void cedulaCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaCliente1ActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed

        String nombreCF = nombreClienteFrecuente.getText();
        String cedulaCF = cedulaClienteFrecuente.getText();
        String fechaNacimientoCF = fechaNacimientoClienteFrecuente.getText();
        String telefonoCF = telefonoClienteFrecuente.getText();
        String generoCF = (String) generoClienteFrecuente.getSelectedItem();
        String provinciaCF = provinciaClienteFrecuente.getText();
        String correoCF = correoClienteFrecuente.getText();
        String ciudadCF = ciudadClienteFrecuente.getText();
        String corregimientoCF = corregimientoClienteFrecuente.getText();
        
        //datos nuevos para frecuentes
        String numeroMembresiaCF = numeroMembresiaFrecuente.getText();
        String productoFrecuentesCF = productoFrecuentes.getText();
        Double productoDescuentoCF = Double.valueOf(productoDescuentoFrecuente.getText());
        Double promedioGastadoCF = Double.valueOf(promedioGastadoFrecuente.getText());

        try {
            Connection con = HikariJDBC.getConnection();

            PreparedStatement ps = con.prepareStatement("INSERT INTO clientes(cedula, tipoCliente, nombre, fechaNacimiento, genero, correo, telefono, provincia, ciudad, corregimiento, numMembresia, cantidadPromedioGastada, productosFrecuentes, descuento) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1, cedulaCF);
            ps.setString(2, tipoF);
            ps.setString(3, nombreCF);
            ps.setString(4, fechaNacimientoCF);
            ps.setString(5, generoCF);
            ps.setString(6, correoCF);
            ps.setString(7, telefonoCF);
            ps.setString(8, provinciaCF);
            ps.setString(9, ciudadCF);
            ps.setString(10, corregimientoCF);
            ps.setString(11, numeroMembresiaCF);
            ps.setDouble(12, promedioGastadoCF);
            ps.setString(13, productoFrecuentesCF);
            ps.setDouble(14, productoDescuentoCF);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Registro Guardado Exitosamente");
            PantallaIngresoClientes pantallaIngreso = PantallaIngresoClientes.getInstance();

            //pantallaIngreso.cargarTabla();
            if (pantallaIngreso != null) {
                pantallaIngreso.cargarTabla();
            }

            ps.close();
            con.close();

            dispose();

        } catch (SQLException e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_registrarActionPerformed

    private void correoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoClienteActionPerformed

    private void telefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoClienteActionPerformed

    private void fechaNacimientoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaNacimientoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaNacimientoClienteActionPerformed

    private void nombreCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCliente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCliente2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDeClienteFrecuente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDeClienteFrecuente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDeClienteFrecuente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDeClienteFrecuente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new RegistroDeClienteFrecuente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarF;
    private javax.swing.JTextField cedulaClienteFrecuente;
    private javax.swing.JTextField ciudadClienteFrecuente;
    private javax.swing.JTextField corregimientoClienteFrecuente;
    private javax.swing.JTextField correoClienteFrecuente;
    private javax.swing.JTextField fechaNacimientoClienteFrecuente;
    private javax.swing.JComboBox<String> generoClienteFrecuente;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField nombreClienteFrecuente;
    private javax.swing.JTextField numeroMembresiaFrecuente;
    private javax.swing.JTextField productoDescuentoFrecuente;
    private javax.swing.JTextField productoFrecuentes;
    private javax.swing.JTextField promedioGastadoFrecuente;
    private javax.swing.JTextField provinciaClienteFrecuente;
    private javax.swing.JButton registrarF;
    private javax.swing.JTextField telefonoClienteFrecuente;
    // End of variables declaration//GEN-END:variables
}
